-- File /home/HN9W0P/AB/hf3_uj/lang/ada/adder.ads
-- generated by Atelier-B/blk on Sat May 14 03:03:14 2016
-- from input file /home/HN9W0P/AB/hf3_uj/lang/ada/adder.str
-- WARNING : "sets#T_1" has been renamed into "array_type_1"
-- WARNING : "sets#T_2" has been renamed into "array_type_1"
-- File adder.str
-- generated by Atelier-B/tbada on Sat May 14 03:03:14 2016
-- from input_file adder.imp, checksum dd671f870c1a47c6996106bc316f9398
-- adder_i
-- * Author: 
-- * Creation date: 2016.05.13.
-- 
with system ;
use system ;
with Unchecked_Conversion ;
with sets ;
use sets ;

package adder is
	
	type TYPE_adder is record
		-- Is instance initialised ?
		initialisation : BOOLEAN ;
	end record ;
	type PTR_adder is access TYPE_adder ;
	--------------------
	-- INITIALISATION --
	--------------------
	procedure IMPORTS(this : in PTR_adder) ; -- Creates imported instances
	procedure INITIALISATION(this : in PTR_adder) ; -- Initialises instances
	----------------
	-- OPERATIONS --
	----------------
	procedure f_osszead(
		this : in PTR_adder ;
		in_tomb: in array_type_1 ;
		osszeg : in out INTEGER) ;
	
end adder ;
