-- File /home/HN9W0P/AB/hf3_uj/lang/ada/basic_io.ads
-- generated by Atelier-B/blk on Sat May 14 03:03:14 2016
-- from input file /home/HN9W0P/AB/BASIC/trad/ada/basic_io.str
--****************************************************************************
--
--Base machine BASIC_IO for ADA target language
--
--(C) 1996 CLEARSY
--
-- Version @(#) basic_io.str version 1.4 (date : 26 Nov 1996) 
--
--****************************************************************************
with system ;
use system ;
with Unchecked_Conversion ;
with sets ;
use sets ;

package BASIC_IO is

	SCCS_ID : CONSTANT STRING := "@(#) basic_io.str version 1.4 (date : 26 Nov 1996)" ;

	type TYPE_BASIC_IO is record
		-- Is instance initialised ?
		initialisation : BOOLEAN ;
		
	end record ;
	
	type PTR_BASIC_IO is access TYPE_BASIC_IO ;
	
	--------------------
	-- INITIALISATION --
	--------------------
	procedure IMPORTS(this : in PTR_BASIC_IO) ; -- Creates imported instances
	procedure INITIALISATION(this : in PTR_BASIC_IO) ; -- Initialises instances
	
	----------------
	-- OPERATIONS --
	----------------
	procedure INTERVAL_READ(
		this : in PTR_BASIC_IO ;
		mm : in INTEGER ;
		nn : in INTEGER ;
		bb : in out INTEGER) ;
	procedure INT_WRITE(this : in PTR_BASIC_IO ; vv : in INTEGER) ;
	procedure BOOL_READ(this : in PTR_BASIC_IO ; bb : in out BOOLEAN) ;
	procedure BOOL_WRITE(this : in PTR_BASIC_IO ; bb : in BOOLEAN) ;
	procedure CHAR_READ(this : in PTR_BASIC_IO ; cc : in out INTEGER) ;
	procedure CHAR_WRITE(this : in PTR_BASIC_IO ; cc : in INTEGER) ;
	procedure STRING_WRITE(this : in PTR_BASIC_IO ; ss : in STRING) ;
	
end BASIC_IO ;


