-- File /home/HN9W0P/AB/hf3_uj/lang/ada/core.ads
-- generated by Atelier-B/blk on Sat May 14 03:03:14 2016
-- from input file /home/HN9W0P/AB/hf3_uj/lang/ada/core.str
-- WARNING : "sets#T_1" has been renamed into "array_type_1"
-- File core.str
-- generated by Atelier-B/tbada on Sat May 14 03:03:14 2016
-- from input_file core.imp, checksum 3bf76bb6b26581e12f43c5ab604ed546
-- core_i
-- * Author: 
-- * Creation date: 2016.05.13.
-- 
with system ;
use system ;
with Unchecked_Conversion ;
with sets ;
use sets ;

-- IMPORTS clause
with counter ;
with adder ;

-- SEES clause
with BASIC_IO ;

package core is
	
	type TYPE_core is record
		-- Is instance initialised ?
		initialisation : BOOLEAN ;
		-- Imported machines
		ref_counter : counter.PTR_counter ;
		ref_adder : adder.PTR_adder ;
		-- Seen machines
		ref_BASIC_IO : BASIC_IO.PTR_BASIC_IO ;
		-- Machine visible variables
		tomb : array_type_1 ;
		darab : INTEGER ;
		osszeg : INTEGER ;
	end record ;
	type PTR_core is access TYPE_core ;
	--------------------
	-- INITIALISATION --
	--------------------
	procedure IMPORTS(this : in PTR_core) ; -- Creates imported instances
	-- SEES BASIC_IO
	procedure SET_BASIC_IO(
		this : in PTR_core ;
		new_BASIC_IO : BASIC_IO.PTR_BASIC_IO) ;
	procedure INITIALISATION(this : in PTR_core) ; -- Initialises instances
	----------------
	-- OPERATIONS --
	----------------
	procedure beir(this : in PTR_core) ;
	procedure muvelet(this : in PTR_core) ;
	procedure kiir(this : in PTR_core) ;
	
	-- Access methods
	function get_tomb(this : in PTR_core) return
		array_type_1 ;
	procedure set_tomb(
		this : in PTR_core ;
		value : array_type_1) ;
	
	function get_darab(this : in PTR_core) return INTEGER ;
	procedure set_darab(
		this : in PTR_core ;
		value : INTEGER) ;
	
	function get_osszeg(this : in PTR_core) return INTEGER ;
	procedure set_osszeg(
		this : in PTR_core ;
		value : INTEGER) ;
	
	-- Access methods are inlined for efficiency
	pragma inline(
		get_tomb,
		set_tomb,
		get_darab,
		set_darab,
		get_osszeg,
		set_osszeg) ;
end core ;
