-- File /home/HN9W0P/AB/hf3_uj/lang/ada/core.adb
-- generated by Atelier-B/blk on Sat May 14 03:03:14 2016
-- from input file /home/HN9W0P/AB/hf3_uj/lang/ada/core.bod
-- WARNING : "sets#T_1" has been renamed into "array_type_1"
-- File core.bod
-- generated by Atelier-B/tbada on Sat May 14 03:03:14 2016
-- from input_file core.imp, checksum 3bf76bb6b26581e12f43c5ab604ed546

-- core_i
-- * Author: 
-- * Creation date: 2016.05.13.
-- 
package body core is
	
	--------------------
	-- INITIALISATION --
	--------------------
	procedure IMPORTS(this : in PTR_core) is
	begin
		-- IMPORTS Clause
		-- IMPORTS counter
		this.ref_counter := new counter.TYPE_counter ;
		counter.IMPORTS(this.ref_counter) ;
		-- IMPORTS adder
		this.ref_adder := new adder.TYPE_adder ;
		adder.IMPORTS(this.ref_adder) ;
		-- Component does not extend any machine
		null ;
		-- Instance is not initialised
		this.initialisation := FALSE ;
	end IMPORTS ;
	-- SEES BASIC_IO
	procedure SET_BASIC_IO(
		this : in PTR_core ;
		new_BASIC_IO : BASIC_IO.PTR_BASIC_IO) is
	begin
		this.ref_BASIC_IO := new_BASIC_IO ;
	end SET_BASIC_IO ;
	procedure INITIALISATION(this : in PTR_core) is
	begin
		if (this.initialisation = TRUE)
		then
			return ;
		end if ;
		this.initialisation := TRUE ;
		-- Initialisation of imported machines
		counter.INITIALISATION(this.ref_counter) ;
		adder.INITIALISATION(this.ref_adder) ;
		-- Initialisation of seen machines
		BASIC_IO.INITIALISATION(this.ref_BASIC_IO) ;
		-- INITIALISATION clause
		this.tomb := (1 .. 10 => 1) ;
		this.darab := 0 ;
		this.osszeg := 0 ;
	end INITIALISATION ;
	----------------
	-- OPERATIONS --
	----------------
	procedure beir(this : in PTR_core) is
		ii : INTEGER ;
		elem : INTEGER ;
	begin
		ii := 1 ;
		--elem := 1;
		while (ii <= 10) loop
			BASIC_IO.INTERVAL_READ(
				this.ref_BASIC_IO,
				1,
				100,
				elem) ;
			this.tomb(ii) := elem ;
			ii := ii + 1 ;
		end loop ;
	end beir ;
	
	procedure muvelet(this : in PTR_core) is
	begin
		counter.f_megszamol(
			this.ref_counter,
			this.tomb,
			this.darab) ;
		adder.f_osszead(
			this.ref_adder,
			this.tomb,
			this.osszeg) ;
	end muvelet ;
	
	procedure kiir(this : in PTR_core) is
	begin
		BASIC_IO.INT_WRITE(this.ref_BASIC_IO, this.darab) ;
		BASIC_IO.STRING_WRITE(this.ref_BASIC_IO, " db paratlan szam van a tombben\n") ;
		BASIC_IO.STRING_WRITE(this.ref_BASIC_IO, "Ezek osszege: ") ;
		BASIC_IO.INT_WRITE(this.ref_BASIC_IO, this.osszeg) ;
		BASIC_IO.STRING_WRITE(this.ref_BASIC_IO, "\n") ;
	end kiir ;
	
	-- Access methods
	function get_tomb(this : in PTR_core) return
		array_type_1 is
	begin
		return this.tomb ;
	end get_tomb ;
	procedure set_tomb(
		this : in PTR_core ;
		value : array_type_1) is
	begin
		this.tomb := value ;
	end set_tomb ;
	
	function get_darab(this : in PTR_core) return INTEGER is
	begin
		return this.darab ;
	end get_darab ;
	procedure set_darab(
		this : in PTR_core ;
		value : INTEGER) is
	begin
		this.darab := value ;
	end set_darab ;
	
	function get_osszeg(this : in PTR_core) return INTEGER is
	begin
		return this.osszeg ;
	end get_osszeg ;
	procedure set_osszeg(
		this : in PTR_core ;
		value : INTEGER) is
	begin
		this.osszeg := value ;
	end set_osszeg ;
	
end core ;
