-- File /home/HN9W0P/AB/hf3_uj/lang/ada/counter.ads
-- generated by Atelier-B/blk on Sat May 14 03:03:14 2016
-- from input file /home/HN9W0P/AB/hf3_uj/lang/ada/counter.str
-- WARNING : "sets#T_1" has been renamed into "array_type_1"
-- WARNING : "sets#T_2" has been renamed into "array_type_1"
-- File counter.str
-- generated by Atelier-B/tbada on Sat May 14 03:03:14 2016
-- from input_file counter.imp, checksum 0135dc33e6b590efc357a632fb76d99f
-- counter_i
-- * Author: 
-- * Creation date: 2016.05.13.
-- 
with system ;
use system ;
with Unchecked_Conversion ;
with sets ;
use sets ;

package counter is
	
	type TYPE_counter is record
		-- Is instance initialised ?
		initialisation : BOOLEAN ;
	end record ;
	type PTR_counter is access TYPE_counter ;
	--------------------
	-- INITIALISATION --
	--------------------
	procedure IMPORTS(this : in PTR_counter) ; -- Creates imported instances
	procedure INITIALISATION(this : in PTR_counter) ; -- Initialises instances
	----------------
	-- OPERATIONS --
	----------------
	procedure f_megszamol(
		this : in PTR_counter ;
		in_tomb: in array_type_1 ;
		db : in out INTEGER) ;
	
end counter ;
