-- File /home/HN9W0P/AB/hf3_uj/lang/ada/counter.adb
-- generated by Atelier-B/blk on Sat May 14 03:03:14 2016
-- from input file /home/HN9W0P/AB/hf3_uj/lang/ada/counter.bod
-- WARNING : "sets#T_1" has been renamed into "array_type_1"
-- WARNING : "sets#T_2" has been renamed into "array_type_1"
-- File counter.bod
-- generated by Atelier-B/tbada on Sat May 14 03:03:14 2016
-- from input_file counter.imp, checksum 0135dc33e6b590efc357a632fb76d99f

-- counter_i
-- * Author: 
-- * Creation date: 2016.05.13.
-- 
package body counter is
	
	--------------------
	-- INITIALISATION --
	--------------------
	procedure IMPORTS(this : in PTR_counter) is
	begin
		-- Component does not import any machine
		null ;
		-- Component does not extend any machine
		null ;
		-- Instance is not initialised
		this.initialisation := FALSE ;
	end IMPORTS ;
	procedure INITIALISATION(this : in PTR_counter) is
	begin
		if (this.initialisation = TRUE)
		then
			return ;
		end if ;
		this.initialisation := TRUE ;
	end INITIALISATION ;
	----------------
	-- OPERATIONS --
	----------------
	procedure f_megszamol(
		this : in PTR_counter ;
		in_tomb: in array_type_1 ;
		db: in out INTEGER) is
		ii : INTEGER ;
		darab : INTEGER ;
		akt : INTEGER ;
		maradek : INTEGER ;
		-- The following variable(s) have been added
		-- in order to avoid aliasing problems when
		-- arrays are being used as in parameters
		tomb : array_type_1 :=
			in_tomb ;
	begin
		ii := 1 ;
		darab := 0 ;
		db := 0 ;
		akt := 0 ;
		maradek := 0 ;
		while (ii /= 11) loop
			akt :=
				tomb(ii) ;
			maradek := akt mod 2 ;
			if (maradek = 1)
			then
				darab := darab +
					1 ;
			end if ;
			ii := ii + 1 ;
		end loop ;
		db := darab ;
	end f_megszamol ;
	
end counter ;
