-- File /home/HN9W0P/AB/hf3_uj/lang/ada/sets.ads
-- generated by Atelier-B/blk on Sat May 14 03:03:14 2016
-- from input file /home/HN9W0P/AB/hf3_uj/lang/ada/sets.str
package sets is
	-- Builtin functions
	function succ(x : in INTEGER) return INTEGER ;
	function pred(x : in INTEGER) return INTEGER ;
	function bool(x : in BOOLEAN) return BOOLEAN ;
	-- Builtin constants
	MAXINT : constant INTEGER := 2147483647 ;
	MININT : constant INTEGER := -2147483647 ;
	-- Array types from machine core
	type array_type_1 is array (1..10) of INTEGER ;
	-- Builtin functions are inlined for efficiency
	pragma inline(succ, pred, bool) ;
end sets ;
