-- File /home/HN9W0P/AB/hf3_uj/lang/ada/sets.adb
-- generated by Atelier-B/blk on Sat May 14 03:03:14 2016
-- from input file /home/HN9W0P/AB/hf3_uj/lang/ada/sets.bod
package body sets is
	function succ(x : in INTEGER) return INTEGER is
	begin
		return x + 1 ;
	end succ ;
	function pred(x : in INTEGER) return INTEGER is
	begin
		return x - 1 ;
	end pred ;
	function bool(x : in BOOLEAN) return BOOLEAN is
	begin
		return x ;
	end bool ;
end sets ;
