-- File /home/feri/AB40_ws1/hf3b/lang/ada/ma.ads
-- generated by Atelier-B/blk on Tue Apr 17 17:43:32 2018
-- from input file /home/feri/AB40_ws1/hf3b/lang/ada/ma.str
-- WARNING : "sets#T_1" has been renamed into "array_type_1"
-- WARNING : "sets#T_2" has been renamed into "array_type_1"
-- WARNING : "sets#T_3" has been renamed into "array_type_1"
-- WARNING : "sets#T_4" has been renamed into "array_type_2"
-- File ma.str
-- generated by Atelier-B/tbada on Tue Apr 17 17:43:32 2018
-- from input_file ma.imp, checksum 425c95290a5ed3dd5d832594a929f60a
-- WARNING : this component has not been fully proved
-- THERE ARE THEREFORE NO GUARANTEES ABOUT THIS FILE

-- ma_i;
-- * Creation date: 2016.03.18.
-- 
with system ;
use system ;
with Unchecked_Conversion ;
with sets ;
use sets ;

-- SEES clause
with BASIC_IO ;

package ma is
	
	type TYPE_ma is record
		-- Is instance initialised ?
		initialisation : BOOLEAN ;
		-- Seen machines
		ref_BASIC_IO : BASIC_IO.PTR_BASIC_IO ;
		-- Machine visible variables
		via1c : BOOLEAN ;
		vib1c : BOOLEAN ;
		tac : array_type_1 ;
		tbc : array_type_1 ;
		tmc : array_type_1 ;
		tuc : array_type_2 ;
		vm : BOOLEAN ;
		viu1 : BOOLEAN ;
	end record ;
	type PTR_ma is access TYPE_ma ;
	--------------------
	-- INITIALISATION --
	--------------------
	procedure IMPORTS(this : in PTR_ma) ; -- Creates imported instances
	-- SEES BASIC_IO
	procedure SET_BASIC_IO(
		this : in PTR_ma ;
		new_BASIC_IO : BASIC_IO.PTR_BASIC_IO) ;
	procedure INITIALISATION(this : in PTR_ma) ; -- Initialises instances
	----------------
	-- OPERATIONS --
	----------------
	procedure init(this : in PTR_ma) ;
	procedure mbe(this : in PTR_ma) ;
	procedure mtrb(this : in PTR_ma) ;
	procedure mtra(this : in PTR_ma) ;
	procedure opm(this : in PTR_ma) ;
	procedure ki(this : in PTR_ma) ;
	
	-- Access methods
	function get_viu1(this : in PTR_ma) return BOOLEAN ;
	procedure set_viu1(this : in PTR_ma ; value : BOOLEAN) ;
	
	-- Access methods are inlined for efficiency
	pragma inline(get_viu1, set_viu1) ;
end ma ;
