-- File /home/feri/AB40_ws1/hf3b/lang/ada/sets.adb
-- generated by Atelier-B/blk on Tue Apr 17 17:43:32 2018
-- from input file /home/feri/AB40_ws1/hf3b/lang/ada/sets.bod
-- WARNING : some components of this project have not been fully proved
-- THERE ARE THEREFORE NO GUARANTEES ABOUT THIS FILE
package body sets is
	function succ(x : in INTEGER) return INTEGER is
	begin
		return x + 1 ;
	end succ ;
	function pred(x : in INTEGER) return INTEGER is
	begin
		return x - 1 ;
	end pred ;
	function bool(x : in BOOLEAN) return BOOLEAN is
	begin
		return x ;
	end bool ;
end sets ;
