-- File /home/feri/AB40_ws1/hf3b/lang/ada/sets.ads
-- generated by Atelier-B/blk on Tue Apr 17 17:43:32 2018
-- from input file /home/feri/AB40_ws1/hf3b/lang/ada/sets.str
-- WARNING : some components of this project have not been fully proved
-- THERE ARE THEREFORE NO GUARANTEES ABOUT THIS FILE
package sets is
	-- Builtin functions
	function succ(x : in INTEGER) return INTEGER ;
	function pred(x : in INTEGER) return INTEGER ;
	function bool(x : in BOOLEAN) return BOOLEAN ;
	-- Builtin constants
	MAXINT : constant INTEGER := 2147483647 ;
	MININT : constant INTEGER := -2147483647 ;
	-- Array types from machine ma
	type array_type_1 is array (1..5) of BOOLEAN ;
	type array_type_2 is array (1..5) of INTEGER ;
	-- Builtin functions are inlined for efficiency
	pragma inline(succ, pred, bool) ;
end sets ;
